### PR TITLE
Full messages

### PR DESCRIPTION
**Pull request by caromedellin**
So we have a chat room for the messages, I also gave them some style, not the definitive one of course but we can easily go from here and move things around. Also added sass! And a helper for the dates.
I don't remember what we discuss about the possibility to edit messages, but I figured that since we are going to add the texting gem, once they are sent there's no going back.

### CODE REVIEW

**Comment by deweydell** [comment]
Hey Carolina, 
I just pulled this on my computer and it looks good at a mobile size, but the layout is messed up when the browser is full size. Does it show that way on your computer? I've attached pictures below. Do you think you could try to fix this layout before we merge?

MOBILE SIZE:
mobile size

FULL SIZE:
computer size

**Comment by caromedellin** [comment]
Oh no! My computer is smaller so that's probably why I didn't see it

**Comment by caromedellin** [comment]
I'll fix it 😄

**Comment by deweydell** [comment]
Cool!!!! Thanks :)

## 

nicolabeuscher.com

On Sun, Jan 31, 2016 at 9:38 AM, Carolina Medellin <notifications@github.com

**Comment by deweydell** [comment]
Omg just seeded messages
screen shot 2016-01-31 at 9 42 57 am

Since you are really good at bootstrap do you think you could make the height of the conversation box a little bigger?

And maybe throw in some padding so the names/circles/message text is not bumping up against one another?

Let me know! 
I really like it though!

**Comment by deweydell** [comment]
From a design perspective, I'm not sure we need the U and Me circles right now, though once we have profile pictures solid we could always add them in at a later date if we wanted.

**Pull request merged**
